### ISSUE TITLE
Minor issues in code samples

### ISSUE THREAD

**Issue by uzluisf** [LaurentRosenfeld/think_raku#3]
In Solutions to the Exercises, [Boyd Duffee found some bugs in the following code samples](https://gitlab.com/uzluisf/piensaperl6/issues/12):

https://github.com/LaurentRosenfeld/think_raku/blob/62af79a8413bb48e64c7a79081979631b1d172dc/book/appendix_solutions.tex#L3103-L3107

The function always returns `False` since the operands, even when they've the same values, the operands are of different types.

https://github.com/LaurentRosenfeld/think_raku/blob/62af79a8413bb48e64c7a79081979631b1d172dc/book/appendix_solutions.tex#L5278-L5281

The `is-leap-year` cannot be called on the role `Dateish`. And when instatiated (`Dateish.new(:year<2016>.is-leap-year`), it fails with `Cannot call Dateish.new with these named parameters: year`.

**Comment by LaurentRosenfeld** [comment]
Yes, I'm pretty sure that both examples were working with the Raku/Perl6 versions available when I made them. I think that these problems have to do with changes made to the language since then.

The first problem probably has to do with the great list refactor that happened in 2016 or 2017. Some of my examples were written before that.

Similarly, I'm pretty sure that this second example used to work at the time. 

Well, in both cases, I'll investigate to find new working examples.

Thank you for letting me know about these problems.

Regards,
Laurent.

**Comment by LaurentRosenfeld** [comment]
I have fixed the two code samples, and added Boyd Duffee to the contributor's list in the Preface.

**Comment by LaurentRosenfeld** [comment]
Please note that I also made the changes to the Think Perl 6 repo.

**Comment by LaurentRosenfeld** [comment]
Closing the issue now.

**Comment by LaurentRosenfeld** [comment]
Since this is now corrected, I close the issue.
